### ISSUE TITLE
Z2UI5_TOOL_CL_UTILITY, generic reference cannot be dereferenced

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2UI5/abap2UI5-tools#3]
Attempting to run this demo on A4H (HANA1909 docker image), handler returns an error pointing to Z2UI5_TOOL_CL_UTILITY, method GET_CSV_BY_TABLE. Same error on slightly older installation NPL (7.52SP04).

Possibly a language version difference?

![immagine](https://github.com/abap2UI5/ext-app_tools/assets/25269970/f886f307-ba81-47ee-bf2c-cf316b3cccce)

**Comment by oblomov-dev** [comment]
Hi @AndreaBorgia-Abo,
sorry somehow i forgot to watch this repository and just see now all your issues.
I updated the repository yesterday again and tested with a lower release. 
Your issue should be solved now.
Best regards.

**Comment by AndreaBorgia-Abo** [comment]
Issue is long gone, closing
