### ISSUE TITLE
Z2UI5_TOOL_CL_APP_00 works on HANA1909, fails on 7.52SP04

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2UI5/abap2UI5-tools#4]
On A4H (HANA1909 docker image) works ok.
On NPL (7.52SP04) the code is invalid
![immagine](https://github.com/abap2UI5/ext-app_tools/assets/25269970/85405917-95f3-43f7-b1d5-bbce755dfb2a)

Possibly a language version difference?

**Comment by oblomov-dev** [comment]
Hi @AndreaBorgia-Abo,
yes this is on a lower release also not working. Thank you for the hint, i changed it and it should also work with the update from yesterday now. you can test again.
best regards.

**Comment by AndreaBorgia-Abo** [comment]
Issue is (long) gone, closing
