### ISSUE TITLE
Z2UI5_TOOL_CL_APP_09 works on HANA1909, fails on 7.52SP04

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [abap2UI5/abap2UI5-tools#5]
On A4H (HANA1909 docker image) works ok.
On NPL (7.52SP04) the code is invalid:
![grafik](https://github.com/abap2UI5/ext-app_tools/assets/25269970/ea8199d9-33dd-4da6-8130-c420f6013ac7)

**Comment by oblomov-dev** [comment]
HI @AndreaBorgia-Abo,
the demo 09 was just a test, i deleted it and this error should not show up anymore.
best regards

**Comment by AndreaBorgia-Abo** [comment]
The [class](https://github.com/abap2UI5/abap2UI5-tools/blob/main/src/z2ui5_cl_tool_app_09.clas.abap) is apparently still there; if this is not related, fell free to close the bugreport: my NPL installation is currently out of service because of VirtualBox issues with recent Linux kernels so I am not able to retest quickly.

**Comment by oblomov-dev** [comment]
Yes the original class is removed but now there is a new one with the same name but different content. I close the issue, good luck with your virtual box and feel free to give it a try again when you are ready.

**Comment by AndreaBorgia-Abo** [comment]
Took me a while but I can confirm that it is ok on NPL, thank you!
