### ISSUE TITLE
DDIC searchhelp generator

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5-tools#7]
Hi oblomov,

I had the requirement to reuse standard and custom DDIC searchhelps in my ABAP2UI5 app.
Therefore I developed an "DDIC sreachhelp generator".
This is just a first version and for sure it missed a lot of functionalities, but I guess it's a good kick-off and a opener for discussion.
Basically its just a simple static method "GENERATE_DDIC_SHLP" to be called in order to generate all the search fields and the result table of a corresponding DDIC searchhelp.
You only need to declare a public structure for the searchhelp input-fields and a public internal table for the searchhelp result in your ABAP2UI5 application class. 

Class: ZCL_ABAP2UI5_UTIL
`
class ZCL_ABAP2UI5_UTIL definition
  public
  final
  create public .

public section.

  class-methods GENERATE_DDIC_SHLP
    importing
      !IR_PARENT type ref to Z2UI5_CL_XML_VIEW
      !IR_CLIENT type ref to Z2UI5_IF_CLIENT
      !IR_CONTROLLER type ref to OBJECT
      !IV_SHLP_ID type SHLPNAME
      !IV_RESULT_ITAB_NAME type CLIKE
      !IV_RESULT_ITAB_EVENT type CLIKE
      !IV_SHLP_FIELDS_STRUC_NAME type CLIKE .
protected section.
private section.
ENDCLASS.

CLASS ZCL_ABAP2UI5_UTIL IMPLEMENTATION.

* <SIGNATURE>---------------------------------------------------------------------------------------+
* | Static Public Method ZCL_ABAP2UI5_UTIL=>GENERATE_DDIC_SHLP
* +-------------------------------------------------------------------------------------------------+
* | [--->] IR_PARENT                      TYPE REF TO Z2UI5_CL_XML_VIEW
* | [--->] IR_CLIENT                      TYPE REF TO Z2UI5_IF_CLIENT
* | [--->] IR_CONTROLLER                  TYPE REF TO OBJECT
* | [--->] IV_SHLP_ID                     TYPE        SHLPNAME
* | [--->] IV_RESULT_ITAB_NAME            TYPE        CLIKE
* | [--->] IV_RESULT_ITAB_EVENT           TYPE        CLIKE
* | [--->] IV_SHLP_FIELDS_STRUC_NAME      TYPE        CLIKE
* +--------------------------------------------------------------------------------------</SIGNATURE>
  METHOD generate_ddic_shlp.
*----------------------------------------------------------------------*
* LOCAL DATA DEFINITION
*----------------------------------------------------------------------*
    DATA: ls_shlp             TYPE  shlp_descr,
          lv_grid_form_no     TYPE i,
          lt_arg              TYPE TABLE OF stringval,
          lv_arg_fieldname    TYPE stringval,
          lv_cell_fieldname   TYPE stringval,
          lv_path_result_itab TYPE stringval,
          lv_path_shlp_fields TYPE stringval.

    FIELD-SYMBOLS: <ls_fielddescr>  TYPE dfies,
                   <ls_fieldprop>   TYPE ddshfprop,
                   <lt_result_itab> TYPE ANY TABLE,
                   <ls_shlp_fields> TYPE any,
                   <lv_field>       TYPE any.

* ---------- Get result itab reference ------------------------------------------------------------
    lv_path_result_itab = 'IR_CONTROLLER->' && iv_result_itab_name.
    ASSIGN (lv_path_result_itab) TO <lt_result_itab>.

* ---------- Get searchhelp input fields structure reference --------------------------------------
    lv_path_shlp_fields = 'IR_CONTROLLER->' && iv_shlp_fields_struc_name.
    ASSIGN (lv_path_shlp_fields) TO <ls_shlp_fields>.

    IF <lt_result_itab> IS NOT ASSIGNED OR
      <ls_shlp_fields> IS NOT ASSIGNED.
      RETURN.
    ENDIF.

* -------------------------------------------------------------------------------------------------
* Searchfield Grid
* -------------------------------------------------------------------------------------------------
    DATA(lr_grid_shlp) = ir_parent->grid( 'L3 M3 S3' )->content( 'layout' ).

* ---------- Create 4 forms (grid columns) --------------------------------------------------------
    DATA(lr_form_shlp_1) = lr_grid_shlp->simple_form( )->content( 'form' ).
    DATA(lr_form_shlp_2) = lr_grid_shlp->simple_form( )->content( 'form' ).
    DATA(lr_form_shlp_3) = lr_grid_shlp->simple_form( )->content( 'form' ).
    DATA(lr_form_shlp_4) = lr_grid_shlp->simple_form( )->content( 'form' ).

* ---------- Get searchhelp description -----------------------------------------------------------
    CALL FUNCTION 'F4IF_GET_SHLP_DESCR'
      EXPORTING
        shlpname = iv_shlp_id
      IMPORTING
        shlp     = ls_shlp.

    LOOP AT ls_shlp-fielddescr ASSIGNING <ls_fielddescr>.
* ---------- Init loop data -----------------------------------------------------------------------
      UNASSIGN: <lv_field>.

* ---------- Get field reference ------------------------------------------------------------------
      ASSIGN COMPONENT <ls_fielddescr>-fieldname OF STRUCTURE <ls_shlp_fields> TO <lv_field>.
      IF <lv_field> IS NOT ASSIGNED.
        CONTINUE.
      ENDIF.

* ---------- Determine grid form number -----------------------------------------------------------
      IF lv_grid_form_no IS INITIAL.
        lv_grid_form_no = 1.
      ELSEIF lv_grid_form_no = 4.
        lv_grid_form_no = 1.
      ELSE.
        lv_grid_form_no = lv_grid_form_no + 1.
      ENDIF.

      CASE lv_grid_form_no.
        WHEN 1.
* ---------- Grid 1--------------------------------------------------------------------------------
* ---------- Set field label ----------------------------------------------------------------------
          lr_form_shlp_1->label( <ls_fielddescr>-scrtext_l ).

* ---------- Set input field ----------------------------------------------------------------------
          CASE <ls_fielddescr>-datatype.
            WHEN 'DATS'.
              lr_form_shlp_1->date_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN 'TIMS'.
              lr_form_shlp_1->time_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN OTHERS.
              lr_form_shlp_1->input( value = ir_client->_bind_edit( <lv_field> ) ).
          ENDCASE.

        WHEN 2.
* ---------- Grid 2--------------------------------------------------------------------------------
* ---------- Set field label ----------------------------------------------------------------------
          lr_form_shlp_2->label( zcl_gu=>get_data_element_labels( iv_data_element = <ls_fielddescr>-rollname ) ).

* ---------- Set input field ----------------------------------------------------------------------
          CASE <ls_fielddescr>-datatype.
            WHEN 'DATS'.
              lr_form_shlp_2->date_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN 'TIMS'.
              lr_form_shlp_2->time_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN OTHERS.
              lr_form_shlp_2->input( value = ir_client->_bind_edit( <lv_field> ) ).
          ENDCASE.

        WHEN 3.
* ---------- Grid 3--------------------------------------------------------------------------------
* ---------- Set field label ----------------------------------------------------------------------
          lr_form_shlp_3->label( zcl_gu=>get_data_element_labels( iv_data_element = <ls_fielddescr>-rollname ) ).

* ---------- Set input field ----------------------------------------------------------------------
          CASE <ls_fielddescr>-datatype.
            WHEN 'DATS'.
              lr_form_shlp_3->date_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN 'TIMS'.
              lr_form_shlp_3->time_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN OTHERS.
              lr_form_shlp_3->input( value = ir_client->_bind_edit( <lv_field> ) ).
          ENDCASE.

        WHEN 4.
* ---------- Grid 4--------------------------------------------------------------------------------
* ---------- Set field label ----------------------------------------------------------------------
          lr_form_shlp_4->label( zcl_gu=>get_data_element_labels( iv_data_element = <ls_fielddescr>-rollname ) ).

* ---------- Set input field ----------------------------------------------------------------------
          CASE <ls_fielddescr>-datatype.
            WHEN 'DATS'.
              lr_form_shlp_4->date_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN 'TIMS'.
              lr_form_shlp_4->time_picker( value  = ir_client->_bind_edit( <lv_field> ) ).
            WHEN OTHERS.
              lr_form_shlp_4->input( value = ir_client->_bind_edit( <lv_field> ) ).
          ENDCASE.

      ENDCASE.
    ENDLOOP.

* ---------- Create table -------------------------------------------------------------------------
    DATA(lr_table) = ir_parent->table( items = ir_client->_bind_edit( <lt_result_itab> ) ).
* ---------- Create Columns -----------------------------------------------------------------------
    DATA(lr_columns) = lr_table->columns( ).

* ---------- Set column ---------------------------------------------------------------------------
    LOOP AT ls_shlp-fielddescr ASSIGNING <ls_fielddescr>.
      lr_columns->column( )->text( zcl_gu=>get_data_element_labels( iv_data_element = <ls_fielddescr>-rollname ) ).
    ENDLOOP.

* ---------- Build export parameter list ----------------------------------------------------------
    LOOP AT ls_shlp-fieldprop ASSIGNING <ls_FIELDPROP> WHERE shlpoutput = abap_true.
* ---------- Init loop data -----------------------------------------------------------------------
      CLEAR: lv_arg_fieldname.

* ---------- Build parameter name -----------------------------------------------------------------
      lv_arg_fieldname = `${` && <ls_FIELDPROP>-fieldname && `}`.

* ---------- Collect output fields ----------------------------------------------------------------
      APPEND lv_arg_fieldname TO lt_arg.
    ENDLOOP.

    DATA(lr_item) = lr_table->items(
        )->column_list_item( type = 'Navigation'  press = ir_client->_event( val    = iv_result_itab_event
                                                                             t_arg  = lt_arg ) ).

* ---------- Set cell content ---------------------------------------------------------------------
    LOOP AT ls_shlp-fielddescr ASSIGNING <ls_fielddescr>.
* ---------- Init loop data -----------------------------------------------------------------------
      CLEAR: lv_cell_fieldname.

* ---------- Build cell name ----------------------------------------------------------------------
      lv_cell_fieldname = `{` && <ls_fielddescr>-fieldname && `}`.

      lr_item->cells( )->text( lv_cell_fieldname ).
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
`

Call of class ZCL_ABAP2UI5:
`
    zcl_cc_abap2ui5_util=>generate_ddic_shlp(
                                              ir_parent                 = [Instance of Z2UI5_CL_XML_VIEW]
                                              ir_client                 = ir_client
                                              ir_controller             = [your main ABAP2UI5 app class]
                                              iv_shlp_id                = [ID of the elementary help from DDIC]
                                              iv_result_itab_name       = [ITAB name for the shlp result]
                                              iv_result_itab_event      = [SHLP result table select event]
                                              iv_shlp_fields_struc_name = [STRUC name of SHLP fields] ).
`

Kind regards
Axel

**Comment by axelmohnen** [comment]
The problem is that the searchhelp has no field maintained for selection (value 0).
Means, that the dialog has no searchhelp fields.
![image](https://github.com/abap2UI5/abap2UI5-tools/assets/22371169/5f7a6b92-7d91-4291-bfb0-066b382befe8)

**Comment by choper725** [comment]
isee, so its not just what you get in the gui..

**Comment by axelmohnen** [comment]
Yes, the searchhelp "DD_VIEW" has an "exit" which calls some specific GUI functions, which are not rendered automatically with 2UI5. 
Just run the searchhelp "DD_VIEW" with TX "SE11" in test mode. It's the same behavior like the DDIC SHLP generator.

**Comment by oblomov-dev** [comment]
this issue git big, i close this one, just open a new one for further questions.
